// Speaker notes for every slide: what is on the slide, what to say, a likely question, a simple answer.
module.exports = [
 { title: "Title",
   on: "Project name, subtitle, and the tech stack line.",
   say: "Hello, I'm presenting the NCT & PubMed Research Intelligence Platform. It helps researchers see what changed on clinical trial pages, understand PubMed papers, and compare clinical trials. I built it with Python, FastAPI, SQLite and the Groq API.",
   q: "Why did you choose this project structure / stack?",
   a: "The assignment named Python, FastAPI and SQLite, so I used those. I kept everything simple so I can explain every part: plain Python for the logic and an LLM only where it adds value." },
 { title: "Problem Statement",
   on: "Five pain points researchers face with ClinicalTrials.gov and PubMed.",
   say: "Researchers manually review ClinicalTrials.gov and PubMed. Trial pages change over time, but the site only says 'updated' - it does not show exactly what changed. Comparing many trials by hand is slow, and papers contain a lot of unstructured text. My project automates these four things.",
   q: "Who is the user of this system?",
   a: "A clinical researcher or analyst who monitors a drug or disease area and wants a quick, structured view instead of opening dozens of pages." },
 { title: "Project Objective",
   on: "Three modules: NCT change tracking, PubMed research intelligence, clinical trial comparator.",
   say: "The platform has three modules inside one FastAPI application. Module 1 tracks versions of an NCT page and lists exact changes. Module 2 searches PubMed, stores articles and uses AI to summarize them. Module 3 takes a drug and an indication and shows a side-by-side comparison of trials.",
   q: "Are the three modules connected?",
   a: "They share one database, one UI and one AI service. Module 1 and 3 both use ClinicalTrials.gov data and the same field names, so a trial can be tracked and compared." },
 { title: "Proposed Solution",
   on: "Three pipelines: NCT change log, PubMed AI summary, trial comparison. Violet boxes use Groq AI; teal boxes are plain Python.",
   say: "Each module is a pipeline. For NCT: download, parse, store in SQLite, compare, show the change log - no AI. For PubMed: extract article data, store it, then Groq produces the summary. For trials: extract in Python, store, Groq explains each trial, and the comparison table is built by Python.",
   q: "Why store data in a database instead of just comparing live?",
   a: "To keep history. To say 'what changed' I must have the older version saved, and storing parsed data also avoids calling the APIs again and again." },
 { title: "Overall Architecture",
   on: "User, HTML/JS UI, FastAPI, three modules, external sources, SQLite, Groq service. Legend shows AI vs non-AI.",
   say: "The user works in a plain HTML/JavaScript UI. It calls FastAPI. FastAPI routes the request to a module, which calls ClinicalTrials.gov or PubMed, saves results in SQLite, and only when needed calls the Groq service. Teal means plain Python, violet means AI. All AI code is in one file.",
   q: "Why is all Groq code in one file?",
   a: "It keeps the AI layer replaceable and easy to test - I can swap the model or provider by changing one file, and tests can fake it." },
 { title: "Technology Stack",
   on: "Table of layers and technologies, plus a note on simplicity.",
   say: "Python and FastAPI for the backend, SQLAlchemy with SQLite locally and PostgreSQL on Supabase in the cloud, Pydantic for validation, BeautifulSoup for HTML parsing. Data comes from the official PubMed and ClinicalTrials.gov APIs. Groq provides the LLM. The frontend is plain HTML, CSS and JavaScript, deployed on Render.",
   q: "Why SQLite?",
   a: "SQLite needs no server, so it is ideal for local development and tests. For the cloud I use Supabase PostgreSQL by changing only DATABASE_URL, because SQLAlchemy hides the difference." },
 { title: "NCT Change Detection",
   on: "Both HTML versions go through the parser to normalized JSON, then compare. Example: eligibility age changed from 18-65 to 18-70 - MODIFIED.",
   say: "Both versions are parsed into the same dictionary shape. Parsing removes banners, scripts and layout, collapses whitespace and ignores case. Then my compare function flattens the dictionaries and labels each field added, removed or modified, with the old value, new value, time and version numbers. This is plain Python - no AI.",
   q: "How do you avoid false changes when only the layout changed?",
   a: "I compare extracted, normalized text rather than HTML. In my sample, the second page has different tags and banners, but only the 9 real changes are reported." },
 { title: "PubMed Module",
   on: "Pipeline: search, PubMed API, article metadata, SQLite, Groq, summary and key findings. Note on figures.",
   say: "I search with the official NCBI E-utilities: esearch returns article IDs and efetch returns XML. I parse the XML in Python and save publications, authors and figures in SQLite. Groq then summarizes the abstract. For open-access articles I also download figures; if the image is available the model sees the image plus caption, otherwise only caption and context, and the UI says which one was used.",
   q: "Can the AI really read images?",
   a: "Groq's Llama 4 Scout model accepts images, so yes when I have the image file. When I don't, I do not pretend - the result is labelled caption/context-based." },
 { title: "Clinical Trial Comparator",
   on: "Pipeline from drug + indication to comparison table, and what Python extracts versus what Groq answers.",
   say: "The researcher enters a drug and an indication. I call the ClinicalTrials.gov API, and Python extracts drugs, doses, arms, phase, design, criteria, outcomes, duration and locations. Groq only answers seven standard questions such as what the trial investigates and what makes it different. The table and the highlighting of differences are also plain Python.",
   q: "Why not let the AI extract the trial fields too?",
   a: "Structured fields are better and cheaper to extract with normal code - it is exact, testable and does not hallucinate. AI is for interpretation, which code cannot do." },
 { title: "Database Design",
   on: "Tables grouped by module with one-to-many relationships.",
   say: "Module 1: one study has many versions and many changes. Module 2: one publication has many authors, figures and AI analyses. Module 3: one trial has analyses. Images are saved as files and the database only keeps their path. Full parsed trials are stored as JSON text plus a few real columns for filtering.",
   q: "What is a one-to-many relationship?",
   a: "One row in a table is linked to many rows in another - for example one NCT study has many versions. It is implemented with a foreign key such as study_id." },
 { title: "API Architecture",
   on: "Table of the main endpoints, with method, path and purpose.",
   say: "FastAPI exposes REST endpoints. POST /api/nct/compare takes two HTML files and returns the change log. GET /api/pubmed/search searches PubMed. POST /api/pubmed/analyze sends an abstract to Groq. GET /api/trials/search finds trials, and POST /api/trials/compare returns the comparison table. /docs shows all of them interactively.",
   q: "What is the difference between GET and POST?",
   a: "GET only reads data. POST sends data, such as files or JSON, for the server to process." },
 { title: "User Interface",
   on: "Four real screenshots: dashboard, NCT change log, PubMed article detail, trial comparison.",
   say: "The UI is plain HTML, CSS and JavaScript served by FastAPI. The dashboard shows counts and shortcuts. The NCT page shows a change table with side-by-side view. The PubMed page shows the abstract, AI summary and figures. The trial page shows a comparison table where rows that differ are highlighted.",
   q: "Why not use React?",
   a: "The UI is simple, and plain JavaScript keeps the project easy to understand and deploy as one app. React would add tooling without much benefit here." },
 { title: "AI Usage",
   on: "Two columns: what is done without AI (Python) and what is done with Groq.",
   say: "This is the key slide. Parsing, extraction, normalization, version comparison, API calls, database work, filtering and the comparison table are normal Python. Groq is used only for article summaries, research interpretation, trial understanding, key findings and figure interpretation. The core engineering is deterministic code; the LLM is an extra intelligence layer.",
   q: "How do you control AI mistakes?",
   a: "The prompt says to use only the given text and answer 'Not stated' if unsure; the output has fixed keys; results are labelled AI-generated; and the important comparison never depends on AI." },
 { title: "Demo Flow",
   on: "Three demos in order: NCT comparison, PubMed summary, trial comparison.",
   say: "Demo 1: compare two NCT versions and show the detected age change. Demo 2: search PubMed, open an article and get the Groq summary. Demo 3: search pembrolizumab with melanoma and compare three trials side by side. Everything also works offline with sample data.",
   q: "What if the internet fails during a demo?",
   a: "I included sample NCT, PubMed and trial data, and a 'use sample data' option, so the demo runs without external APIs." },
 { title: "Future Enhancements",
   on: "Ten possible improvements.",
   say: "Next steps are S3, R2 or Supabase Storage for images, scheduled NCT monitoring with email alerts, better image analysis, authentication, advanced search, similarity-based trial discovery, cloud deployment and an analytics dashboard. I would also run the live APIs for a longer period and harden the parsers.",
   q: "What is the biggest limitation today?",
   a: "The live external APIs need a networked test run and AI output needs human review. Files such as figure images are on Render's temporary disk and need S3-style storage; the data itself is safe in Supabase." },
];
